emojis

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,114 +1,24 @@
-version: 2
+version: 2.0
 jobs:
-  test:
+  build:
     docker:
     - image: circleci/node:10
     steps:
     - checkout
+    - run: ls
     - run:
+        name: use emojies 🔧
         command: |
-          mkdir -p tests/folderone/tests
-          mkdir -p tests/foldertwo/tests
-          mv junit.xml tests/folderone/tests/junit.xml
-          mv junit2.xml tests/foldertwo/tests/junit.xml
-    - store_test_results:
-        path: tests
-  sign-adhoc:
-    docker:
-    - image: circleci/node:10
-    steps:
-    - run:
-        command: echo "hi"
-  sign-store:
-    docker:
-    - image: circleci/node:10
-    steps:
-    - run:
-        command: echo "hi"
+          if [ -f ignoredFile ]; then
+            echo "Found ignored file, fialing builds"
+            exit 1
+          fi
+          if [ ! -f "file with spaces" ]; then
+            echo "file with spaces not found, fialing builds"
+            exit 1
+          fi
 workflows:
-  sign-it:
-    jobs:
-    - test
-    - approve-adhoc:
-        type: approval
-        requires:
-        - test
-    - approve-store:
-        type: approval
-        requires:
-        - test
-    - sign-adhoc:
-        requires:
-        - approve-adhoc
-    - sign-store:
-        requires:
-        - approve-store
   version: 2
-
-# Original config.yml file:
-# # Orb 'circleci/hello-build@0.0.10' resolved to 'circleci/hello-build@0.0.10'
-# version: 2.1
-# 
-# workflows:
-#   sign-it:
-#     jobs:
-#     - test      
-#     - approve-adhoc:
-#         type: approval
-#         requires:
-#           - test
-#       
-#     - approve-store:
-#         type: approval
-#         requires:
-#           - test
-#       
-#     - sign-adhoc:
-#         requires:
-#           - approve-adhoc
-#       
-#     - sign-store:
-#         requires:
-#           - approve-store
-# 
-#   version: 2
-# 
-# jobs:
-#   test:
-#     docker:
-#     - image: circleci/node:10
-#     steps:
-#     - checkout
-#     - run: |
-#         mkdir -p tests/folderone/tests
-#         mkdir -p tests/foldertwo/tests
-#         mv junit.xml tests/folderone/tests/junit.xml
-#         mv junit2.xml tests/foldertwo/tests/junit.xml
-#        
-#     - store_test_results:
-#         path: tests
-# 
-# 
-#   approve-adhoc:
-#     docker:
-#     - image: circleci/node:10
-#     steps:
-#     - run: echo \"hi\"
-# 
-#   approve-store:
-#     docker:
-#     - image: circleci/node:10
-#     steps:
-#     - run: echo \"hi\"
-# 
-#   sign-adhoc:
-#     docker:
-#     - image: circleci/node:10
-#     steps:
-#     - run: echo \"hi\"
-# 
-#   sign-store:
-#     docker:
-#     - image: circleci/node:10
-#     steps:
-#     - run: echo \"hi\"
+  workflow:
+    jobs:
+    - build
